const productos = [
    { nombre: "Manzanas Golden", descripcion: "Manzanas frescas y crujientes de origen nacional", categoria: "Frutas", precio: 2.5 },
    { nombre: "Plátanos de Canarias", descripcion: "Plátanos dulces y nutritivos", categoria: "Frutas", precio: 1.8 },
    { nombre: "Naranjas Valencianas", descripcion: "Naranjas jugosas para zumo o mesa", categoria: "Frutas", precio: 2.0 },
    { nombre: "Leche Entera", descripcion: "Leche fresca pasteurizada", categoria: "Lácteos", precio: 1.2 },
    { nombre: "Yogur Natural", descripcion: "Yogur natural sin azúcares añadidos", categoria: "Lácteos", precio: 0.9 },
    { nombre: "Queso Manchego", descripcion: "Queso curado de oveja", categoria: "Lácteos", precio: 7.5 },
    { nombre: "Filetes de Pollo", descripcion: "Pechugas de pollo fileteadas", categoria: "Carnes", precio: 8.0 },
    { nombre: "Carne Picada de Ternera", descripcion: "Carne fresca ideal para albóndigas o hamburguesas", categoria: "Carnes", precio: 9.0 },
    { nombre: "Costillas de Cerdo", descripcion: "Costillas frescas para asar o guisar", categoria: "Carnes", precio: 6.5 },
    { nombre: "Pescado Merluza", descripcion: "Merluza fresca de lonja", categoria: "Pescados", precio: 12.0 },
    { nombre: "Gambas Peladas", descripcion: "Gambas congeladas listas para cocinar", categoria: "Pescados", precio: 15.0 },
    { nombre: "Atún en Aceite", descripcion: "Conserva de atún en aceite de oliva", categoria: "Conservas", precio: 3.0 },
    { nombre: "Pan Integral", descripcion: "Pan de trigo integral recién horneado", categoria: "Panadería", precio: 1.5 },
    { nombre: "Baguette Tradicional", descripcion: "Baguette crujiente de harina blanca", categoria: "Panadería", precio: 1.2 },
    { nombre: "Donuts Glaseados", descripcion: "Rosquillas dulces con glaseado de azúcar", categoria: "Panadería", precio: 2.5 },
    { nombre: "Arroz Basmati", descripcion: "Arroz aromático de grano largo", categoria: "Cereales", precio: 3.0 },
    { nombre: "Espaguetis", descripcion: "Pasta italiana de trigo duro", categoria: "Cereales", precio: 1.8 },
    { nombre: "Cereales de Avena", descripcion: "Copos de avena 100% naturales", categoria: "Cereales", precio: 2.0 },
    { nombre: "Aceite de Oliva Virgen Extra", descripcion: "Aceite de oliva de primera extracción en frío", categoria: "Aceites", precio: 5.0 },
    { nombre: "Aceite de Girasol", descripcion: "Aceite vegetal ideal para freír", categoria: "Aceites", precio: 3.0 },
    { nombre: "Mantequilla", descripcion: "Mantequilla natural sin sal", categoria: "Lácteos", precio: 2.5 },
    { nombre: "Galletas Digestive", descripcion: "Galletas de trigo con alto contenido en fibra", categoria: "Snacks", precio: 2.0 },
    { nombre: "Patatas Chips", descripcion: "Patatas fritas clásicas", categoria: "Snacks", precio: 1.5 },
    { nombre: "Chocolate Negro 70%", descripcion: "Tableta de chocolate amargo", categoria: "Dulces", precio: 2.0 },
    { nombre: "Miel de Flores", descripcion: "Miel natural de flores silvestres", categoria: "Dulces", precio: 6.0 },
    { nombre: "Huevos Camperos", descripcion: "Huevos frescos de gallinas criadas en libertad", categoria: "Huevos", precio: 3.0 },
    { nombre: "Café Molido", descripcion: "Café tostado y molido de alta calidad", categoria: "Bebidas", precio: 4.5 },
    { nombre: "Té Verde", descripcion: "Té verde en hojas sueltas", categoria: "Bebidas", precio: 3.5 },
    { nombre: "Zumo de Naranja Natural", descripcion: "Zumo fresco y sin conservantes", categoria: "Bebidas", precio: 2.5 },
    { nombre: "Agua Mineral", descripcion: "Botella de agua natural sin gas", categoria: "Bebidas", precio: 0.8 },
    { nombre: "Refresco de Cola", descripcion: "Lata de refresco con gas", categoria: "Bebidas", precio: 1.2 },
    { nombre: "Cerveza Artesanal", descripcion: "Cerveza elaborada con ingredientes naturales", categoria: "Bebidas", precio: 2.5 },
    { nombre: "Vino Tinto Rioja", descripcion: "Botella de vino crianza", categoria: "Bebidas", precio: 8.0 },
    { nombre: "Harina de Trigo", descripcion: "Harina fina ideal para repostería", categoria: "Repostería", precio: 1.2 },
    { nombre: "Azúcar Moreno", descripcion: "Azúcar sin refinar con sabor a melaza", categoria: "Repostería", precio: 1.8 },
    { nombre: "Levadura en Polvo", descripcion: "Levadura química para postres", categoria: "Repostería", precio: 1.0 },
    { nombre: "Sal Maldon", descripcion: "Sal marina en escamas", categoria: "Especias", precio: 3.5 },
    { nombre: "Pimienta Negra Molida", descripcion: "Pimienta molida fresca", categoria: "Especias", precio: 2.0 },
    { nombre: "Orégano Seco", descripcion: "Hierba aromática para pizzas y ensaladas", categoria: "Especias", precio: 1.5 },
    { nombre: "Garbanzos", descripcion: "Legumbres secas de alta calidad", categoria: "Legumbres", precio: 2.0 },
    { nombre: "Lentejas Pardinas", descripcion: "Lentejas pequeñas y rápidas de cocinar", categoria: "Legumbres", precio: 1.8 },
    { nombre: "Alubias Blancas", descripcion: "Judías blancas secas", categoria: "Legumbres", precio: 2.2 },
    { nombre: "Tomates en Conserva", descripcion: "Tomates pelados en su jugo", categoria: "Conservas", precio: 1.5 },
    { nombre: "Atún Claro en Aceite", descripcion: "Lomos de atún en conserva", categoria: "Conservas", precio: 3.5 },
    { nombre: "Sardinas en Aceite", descripcion: "Sardinas en conserva con aceite de oliva", categoria: "Conservas", precio: 2.5 },
    { nombre: "Nueces Peladas", descripcion: "Nueces naturales sin cáscara", categoria: "Frutos Secos", precio: 5.0 },
    { nombre: "Almendras Crudas", descripcion: "Almendras naturales sin sal", categoria: "Frutos Secos", precio: 4.5 },
    { nombre: "Mix de Frutos Secos", descripcion: "Mezcla de frutos secos y pasas", categoria: "Frutos Secos", precio: 6.0 },
  ];